---

  - name: run docker mesos slave
    docker:
      name: mesos-slave
      image: mesoscloud/mesos-slave:0.24.1-centos-7
      state: reloaded
      restart_policy: always
      privileged: true
      net: host
      env:
        MESOS_HOSTNAME: "{{ inventory_hostname }}"
        MESOS_IP: "{{ inventory_hostname }}"
        MESOS_MASTER: "zk://{{ zk_nodes }}/mesos"
        MESOS_EXECUTOR_REGISTRATION_TIMEOUT: "10mins"
        MESOS_LOG_DIR: "/var/log/mesos"
      volumes:
        - "/sys/fs/cgroup:/sys/fs/cgroup"
        - "/var/run/docker.sock:/var/run/docker.sock"
    tags:
      -docker
      - slave
