zookeeper:
  image: mesoscloud/zookeeper:3.4.6-centos-7
  net: host
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
  environment:
    MYID: 1
    SERVERS: 192.168.99.101

mesos_master:
  image: mesoscloud/mesos-master:0.24.1-centos-7
  privileged: true
  net: host
  environment:
    - MESOS_HOSTNAME=192.168.99.101
    - MESOS_IP=192.168.99.101
    - MESOS_ZK=zk://localhost:2181/mesos
    - MESOS_LOG_DIR=/var/log/mesos
    - MESOS_QUORUM=1
    - MESOS_REGISTRY=in_memory
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_CLUSTER=MesosCluster

mesos_slave:
  image: mesoscloud/mesos-slave:0.24.1-centos-7
  privileged: true
  net: host
  ports:
    - "5051:5051"
  environment:
    - MESOS_HOSTNAME=192.168.99.101
    - MESOS_MASTER=zk://localhost:2181/mesos
    - MESOS_LOG_DIR=/var/log/mesos
    - MESOS_LOGGING_LEVEL=INFO

marathon:
  image: mesoscloud/marathon:0.11.0-centos-7
  ports:
    - "8080:8080"
  environment:
    - MARATHON_HOSTNAME=192.168.99.101
    - MARATHON_ZK=zk://localhost:2181/marathon
    - MARATHON_MASTER=zk://zk:2181/mesos
