---

- hosts: localhost
  connection: local
  vars:
    api_token_l: "TOKEN"
  tasks:
  - name: install python dopy (run ansible-playbook with -K ! )
    sudo: yes
    pip:
      name: dopy
  - name: spin up servers
    digital_ocean:
      state: present
      command: droplet
      name: "host-01"
      api_token: "{{ api_token_l }}"
      size_id: "1gb"
      region_id: "lon1"
      id: "14486461"
      image_id: "docker"
      ssh_key_ids: "id_rsa"
    register: my_droplet
  - debug: msg="ID is {{ my_droplet.droplet.id }}"
  - debug: msg="IP is {{ my_droplet.droplet.ip_address }}"
