---

  - hosts: nodes
    remote_user: root
    roles:
      - zookeeper

  - hosts: node-01
    remote_user: root
    roles:
      - mesos-master

  - hosts: nodes
    remote_user: root
    roles:
      - mesos-slave

  - hosts: node-01
    remote_user: root
    roles:
      - marathon

  - hosts: node-01
    remote_user: root
    roles:
      - chronos
